{{- range $service, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my_awesome_app.name" . }}
  labels:
    {{- include "my_awesome_app.labels" . | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my_awesome_app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my_awesome_app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .fullnameOverride }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          command: ["/bin/sh", "-c"]
          args: ["{{ .entrypoint_args }}"]
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            {{- toYaml .env_vars | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .liveness_path }}
              port: {{ .port }}
          readinessProbe:
            httpGet:
              path: {{ .readiness_path }}
              port: {{ .port }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
