{{- range $service, $val := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my_awesome_app.name" . }}
  labels:
    {{- include "my_awesome_app.labels" . | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my_awesome_app.selectorLabels" . | nindent 4 }}
{{- end }}
